import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smart Trader",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession()
    if (!session || !session.user) {
        redirect("/api/auth/signin")
    }
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>My Nav Bar</nav>
        {children}
      </body>
    </html>
  );
}
