name: Deploy Next.js application

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Create .env file
              run: echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env && echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env && echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env && echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env && echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env && echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
            - name: Build docker image
              run: docker build -t jarrodschilling/trade_stats_pro .
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            - name: Publish image to docker hub
              run: docker push jarrodschilling/trade_stats_pro:latest
    
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull jarrodschilling/trade_stats_pro:latest
            - name: Delete old container
              run: docker rm -f tradestatspro-container
            - name: Run docker container
              run: docker run -d -p 3000:3000 --name tradestatspro-container jarrodschilling/trade_stats_pro